### ISSUE TITLE
How can I  add a LandmarkHead to the net , could you give some advice , please ?

### ISSUE THREAD

**Issue by xscjun** [youngwanLEE/CenterMask#10]
Thanks for your great work, I can train the net with the codes now.
How can I  add a LandmarkHead to the net , could you give some advice , please ?

**Comment by youngwanLEE** [comment]
@xscjun 

Hi, 

I have not implemented landmark yet. So I cannot give you proper advice.

When I searched landmark implementation based on maskrcnn-benchmark code, I Couldn't find any project.

I'm sorry I can't help you. :(

**Comment by xscjun** [comment]
> @xscjun
> 
> Hi,
> 
> I have not implemented landmark yet. So I cannot give you proper advice.
> 
> When I searched landmark implementation based on maskrcnn-benchmark code, I Couldn't find any project.
> 
> I'm sorry I can't help you. :(

Thank you all the same !
