### ISSUE TITLE
Where did instance norm added?

### ISSUE THREAD

**Issue by jinfagang** [youngwanLEE/CenterMask#13]
HI, I wanna deploy centermask on tensorrt, I have converted model to onnx.

but when convert onnx2trt I got a error:

```
 In function importInstanceNormalization:
[8] Assertion failed: !isDynamic(tensor_ptr->getDimensions()) && "InstanceNormalization does not support dynamic inputs!"

```

You may not familiar with tensorrt, but can you tell me where did you add instancenorm in code? I searched a round and I can not locate where is it.

BTW, does instance norm dim is dynamic or not?

**Comment by youngwanLEE** [comment]
@jinfagang 

To my knowledge, I didn't use instance norm. 

That's weird :(

**Comment by jinfagang** [comment]
Oh, that .... why torch.onnx.export traced InstanceNorm and I indeed found such node in exported onnx model.

Same behavior I found with FCOS as well. Also EmbedMask generates such a node.

Can u found where it might casued torch.onnx traced InstanceNorm?

**Comment by youngwanLEE** [comment]
@jinfagang 

I'm sorry. I can't help you to find what the problem is on ONNX now due to other works.

**Comment by jinfagang** [comment]
thanks, I found that onnx trace GroupNorm with InstanceNorm.
