### ISSUE TITLE
Why is the order of "P3-P7" different to other papers?

### ISSUE THREAD

**Issue by wangg12** [youngwanLEE/CenterMask#14]

**Comment by youngwanLEE** [comment]
@wangg12 
I can't understand what you mean. 

Could you explain detail?

**Comment by wangg12** [comment]
![image](https://user-images.githubusercontent.com/9958446/72985495-61c08200-3de6-11ea-8cf0-2193095ada30.png)

**Comment by wangg12** [comment]
![image](https://user-images.githubusercontent.com/9958446/72985789-080c8780-3de7-11ea-9c16-60e0d78eead4.png)

**Comment by youngwanLEE** [comment]
@wangg12 
I just draw the figure simply because of the figure size.

However, it is same as the FPN module in FCOS or other papers.

**Comment by wangg12** [comment]
I see. The numbers usually represent feature strides, but yours are just random numbers.
