### ISSUE TITLE
CPU version not implemented - ml_nms

### ISSUE THREAD

**Issue by Sunchax** [youngwanLEE/CenterMask#16]
Hey!

I was wondering if there is any ETA on a possible CPU implementation of the ml_nms.cu for forward-passes on the CPU? Would be nice to be able to run the demo on CPU.

Kindly,
Christoffer

**Comment by youngwanLEE** [comment]
@Sunchax Hi,

Currently, we don't have such plans.

The ML_NMS code originates from [FCOS](https://github.com/tianzhi0549/FCOS) and you can ask for the original author.

**Comment by Sunchax** [comment]
Okay, thank you for a quick reply! 

Btw, CenterMask works very well. Thanks for the work and sharing the code

**Comment by youngwanLEE** [comment]
@Sunchax thanks

Have fun :)
