### ISSUE TITLE
when will you open your implementation based on Detectron2?

### ISSUE THREAD

**Issue by TengFeiHan0** [youngwanLEE/CenterMask#19]
thank you for your considerable work. by the way, when will you open your source code based on detectron2?

**Comment by youngwanLEE** [comment]
@TengFeiHan0 
We may be able to release our centermask2 on top of detectron2 in 2 weeks.

**Comment by jinfagang** [comment]
@youngwanLEE  any updates on centermask2?

**Comment by youngwanLEE** [comment]
@jinfagang 
We have finished the implementation of centermask2 and is training the centermask2 with VoVNet. 

After the training, we'll release the code and models together.
