### ISSUE TITLE
Updates regarding Detectron2

### ISSUE THREAD

**Issue by deepseek** [youngwanLEE/CenterMask#23]
@youngwanLEE 
Any updates regarding the detectron2 implementation?

**Comment by youngwanLEE** [comment]
@deepseek 

The release of centermask2 is imminent.

Stay tuned !!

I have been refactoring the code and writing README.md file.

**Comment by youngwanLEE** [comment]
@deepseek 

We open the [centermask2](https://github.com/youngwanLEE/centermask2) now!

Have fun 👍
