### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by qgh1223** [youngwanLEE/CenterMask#24]
I have one 2080 titan.I have set the IMG_PER_BATCH=2 and change image size to 512.Why I also met cuda out of memory?

**Comment by youngwanLEE** [comment]
What kind of the model you use?

Why don't you use the smallest model, CenterMask-Lite with VoVNet-19 backbone?

**Comment by qgh1223** [comment]
Why cannot use centermask_R_50_FPN_1x?I want to test your model on ISAID dataset.

**Comment by qgh1223** [comment]
I also cannot use centermask_R_50_FPN_lite_res600_ms_bs16_4x

**Comment by youngwanLEE** [comment]
I don't know the ISAID dataset and your environment. 

I recommend when you come across the OOM, reducing input resolution/batch size or change lightweight models.
