### ISSUE TITLE
Training on Cityscapes

### ISSUE THREAD

**Issue by abhigoku10** [youngwanLEE/CenterMask#25]
@youngwanLEE @lsrock1  thanks for sharing your wonderful wanted to knw if you have done any experiements / training on Cityscapes dataset , can your share your results and pretrained modesl ??

**Comment by youngwanLEE** [comment]
@abhigoku10

Sorry, i didn't experiment on Cityscapes and don't plan to train on Cityscapes yet.

Why don't you use [centermask2](https://github.com/youngwanLEE/centermask2) following [detectron2's Cityscapes](https://github.com/facebookresearch/detectron2/tree/master/configs/Cityscapes) ?

**Comment by youngwanLEE** [comment]
@abhigoku10 
Since there are no responses, this issue is closed. 

If you have any questions, feel free to re-open this issue.

**Comment by TengFeiHan0** [comment]
Dear @youngwanLEE  I have trained your centermask model on cityscapes without any modifications.  However, all metrics are zero. Then I realized that centermask is based on  FOCS, a fully convolutional network object detector. but the cityscape doesn't have labels or `gt` for object detection. That's maybe the reason why I couldn't get any results.  Do you have any suggestions?

**Comment by youngwanLEE** [comment]
@TengFeiHan0 

How about using [centermask2](https://github.com/youngwanLEE/centermask2) based on [detectron2](https://github.com/facebookresearch/detectron2) that supports training on Cityscapes?

**Comment by TengFeiHan0** [comment]
I haven't tried it, but in my opinion,  `detectron2` is a high-integrated framework. Probably its training time or inference time is smaller than `maskrcnn-benchmark`. However, it's difficult to deploy my own ideas. Anyway, I will try to train centermask based on detectron2. @youngwanLEE
