### ISSUE TITLE
segmentation performance is  low

### ISSUE THREAD

**Issue by zhenyouwei** [youngwanLEE/CenterMask#26]
Hi，I use the v39_ Lite model you released to test COCO2017 val dataset, the detection accuracy is right but the segmentation accuracy is particularly low. The average value is only about 0.11. Can you tell me what's the reason? Is there any problem in my test? Thank you very much for answering my questions~~

**Comment by youngwanLEE** [comment]
I can't understand why your problem happens.

When I evaluate the CenterMask_Lite_V39 model on COCO val2017, I could get this result.

This result on COCO 2017 usually is lower than [that on test-dev2017](https://github.com/youngwanLEE/CenterMask#coco-test-dev-results).

![image](https://user-images.githubusercontent.com/13238578/75833326-0d082200-5dfc-11ea-9ad9-4f8d0bac277e.png)

**Comment by zhenyouwei** [comment]
I compared the parameters in config. There is a problem with the‘ conv layers “parameter in maskiou head. I used to set it a  wrong value. I  have corrected it to (128,128) and got the correct result.Thanks for your answer.
