### ISSUE TITLE
error: command 'D:\\VisualStudio\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by qiangqing** [youngwanLEE/CenterMask#36]
when i run:
cd CenterMask
python setup.py build develop
I have a problem:
D:\Anaconda3\envs\centermask\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(624): note: see reference to class template instantiation 'c10::ArrayRef<c10::IValue>' being compiled
error: command 'D:\\VisualStudio\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

both my evironment and virtual evironment according your readme.md all have the problom.
my pytorch is 1.4.0
thanks very much your answer

**Comment by nicejava** [comment]
Replace extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'], 
To extra_compile_args={'gcc': ['/Qstd=c99']},

ext_modules = [
    Extension(
        'pycocotools._mask',
        sources=['../common/maskApi.c', 'pycocotools/_mask.pyx'],
        include_dirs = [np.get_include(), '../common'],
        #extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'],
	extra_compile_args={'gcc': ['/Qstd=c99']},
    )
]

**Comment by qiangqing** [comment]
Thanks very much.@nicejava
