### ISSUE TITLE
how to use my own dataset?

### ISSUE THREAD

**Issue by yuchieh0710** [youngwanLEE/CenterMask#37]
Excuse me, as title i want to train centermask on my own dataset. i already prepared my own dataset according to COCO format. But i dont know where the code i should change or how to package the data. Can you tell me how to do this work? Thank you.

**Comment by QuocThangNguyen** [comment]
Hi @yuchieh0710, I have trained my own dataset using CenterMask successfully. Here are the steps to add your dataset:

1. Put your data in the directory `CenterMask/datasets/` 
2. Modify `CenterMask/maskrcnn_benchmark/config/paths_catalog.py`: in class `DatasetCatalog`, add your dataset's name similarly to the existing coco datasets. Note that your dataset's name *must* have the word "coco" in it. 
3. In `CenterMask/configs`, replace these lines in your yaml config file with your dataset's name in `paths_catalog.py`
```
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
```

**Comment by yuchieh0710** [comment]
@QuocThangNguyen OK, i will try it. Thank u so much!!!!
