### ISSUE TITLE
it is error to download the weight file

### ISSUE THREAD

**Issue by qinghuizhao** [youngwanLEE/CenterMask#5]
error link ？ https://dl.dropbox.com/s/2enqxenccz4xy6l/centermask-lite-R-50-ms-bs32-1x.pth

**Comment by qinghuizhao** [comment]
谢谢，已解决。

**Comment by qinghuizhao** [comment]
thanks，this problem is solved。

**Comment by wjjouc** [comment]
this problem is not solved
