### ISSUE TITLE
Where could i download the pretrained models?

### ISSUE THREAD

**Issue by zyf12389** [youngwanLEE/CenterMask#7]
Links left here are invalid. Looking forward to your reply.

**Comment by youngwanLEE** [comment]
@shoutOutYangJie,

Because of Dropbox policy,  the direct link was changed.

Now, you can download the weight.

And we'll open our VoVNet models soon. 

Stay tune and have fun with CenterMask :)

**Comment by shoutOutYangJie** [comment]
> @shoutOutYangJie,
> 
> Because of Dropbox policy, the direct link was changed.
> 
> Now, you can download the weight.
> 
> And we'll open our VoVNet models soon.
> 
> Stay tune and have fun with CenterMask :)

I still can not access dropBox link.
