### ISSUE TITLE
Can you share the pretrained model to Google drive?

### ISSUE THREAD

**Issue by wjjouc** [youngwanLEE/CenterMask#8]

**Comment by youngwanLEE** [comment]
@wjjouc 

Can't you access the dropbox link?

**Comment by shoutOutYangJie** [comment]
@youngwanLEE  I can not access this given link. Please upload weights into Google drive. Link is invalid now.

**Comment by youngwanLEE** [comment]
@shoutOutYangJie 

In my side, I can access the link now.

It is weird you cannot acces the link :(

**Comment by wjjouc** [comment]
> @wjjouc
> 
> Can't you access the dropbox link?
dropbox link cannot be opened

**Comment by wjjouc** [comment]
> @shoutOutYangJie
> 
> In my side, I can access the link now.
> 
> It is weird you cannot acces the link :(
The dropbox link cannot be opened

**Comment by shoutOutYangJie** [comment]
@youngwanLEE 
Nearly four issues is link problem.  Whether link is valid or not,, please upload your three model into google drive, so we can enjoy this amazing centermask.

**Comment by youngwanLEE** [comment]
@shoutOutYangJie 

We update the README and now you can access the weights by google drive.

Have fun :)

**Comment by zimenglan-sysu-512** [comment]
hi @youngwanLEE how could i download the pretrained models trained on the imagenet?
